services:
  api:
    build:
      context: .
      dockerfile: prod.dockerfile
    container_name: api_java
    #env_file:
    # - .env
    environment:
      API_KEY: azertyuiop
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      DB_NAME: graphql_api
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
      - "35729:35729"

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: graphql_api

    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: